// src/components/PdfViewer.vue
<template>
  <div ref="container" class="h-full" />
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'

const props = defineProps<{
  src: string
  filename: string
  licenseKey?: string
}>()

const container = ref<HTMLElement | null>(null)

onMounted(async () => {
  if (!container.value) return
  const { default: PdfjsExpressViewer } = await import('@pdftron/pdfjs-express-viewer')
  PdfjsExpressViewer(
    {
      licenseKey: props.licenseKey,
      initialDoc: props.src,
      filename: props.filename,
    },
    container.value,
  )
})
</script>

// src/components/PdfViewer.tsx
import { useRef, useEffect } from 'react'

interface Props {
  src: string
  filename: string
  licenseKey?: string
}

export default function PdfViewer({ src, filename, licenseKey }: Props) {
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!containerRef.current) return
    const el = containerRef.current
    import('@pdftron/pdfjs-express-viewer').then(({ default: PdfjsExpressViewer }) => {
      PdfjsExpressViewer({ licenseKey, initialDoc: src, filename }, el)
    })
  }, [])

  return <div ref={containerRef} className="h-full" />
}
